---
title: "non-synchronized HeLa cells"
output: pdf_document
date: "2023-04-24"
---

```{r}
MS_Table <- read.table("~/Downloads/RDeeP_HeLa_NS.csv", header=TRUE, row.names=1, sep = ";")
```

```{r}
head(rownames(MS_Table),12)

rownames(MS_Table[2, ])

View(MS_Table)
```

```{r}
dim(MS_Table)
```

```{r}
ctrl = MS_Table[seq(1, ncol(MS_Table), by = 2)] #Nur Control Replicates 
rnase = MS_Table[seq(2, ncol(MS_Table), by = 2)] #Nur RNase Replicates 

#weiteres Auftrennen um es leichter zu haben Zeilen zu finden 
ctrl1 = ctrl[seq(1, ncol(ctrl), by = 3)]
ctrl2 = ctrl[seq(2, ncol(ctrl), by = 3)]
ctrl3 = ctrl[seq(3, ncol(ctrl), by = 3)]

rnase1 = rnase[seq(1, ncol(ctrl), by = 3)]
rnase2 = rnase[seq(2, ncol(ctrl), by = 3)]
rnase3 = rnase[seq(3, ncol(ctrl), by = 3)]

```

```{r}
# Null Zeilen finden 
# which und apply geht durch alle zeile durch un rechnet die summen zusammen, um die zeilen zu finden dessen summe 0 ist 
remove_ctrl1 = which(apply(ctrl1, 1, sum) == 0)
remove_ctrl2 = which(apply(ctrl2, 1, sum) == 0)
remove_ctrl3 = which(apply(ctrl3, 1, sum) == 0)

remove_rnase1 = which(apply(rnase1, 1, sum) == 0)
remove_rnase2 = which(apply(rnase2, 1, sum) == 0)
remove_rnase3 = which(apply(rnase3, 1, sum) == 0)

#Null Zeilen entfernen
# einen vektor mit alles gefundenen Nullstellen füllen, um dann diese alle aus dem Dataframe auf einmal zu entfernen 
zeros_ctrl = c(remove_ctrl1, remove_ctrl2, remove_ctrl3, remove_rnase1, remove_rnase2, remove_rnase3) #Vektor, der mit allen gefundenen Nullen gefüllt ist  
ctrl_zeros = ctrl[-zeros_ctrl,] #neue Control data frame mit entfernten Nullen 

zeros_rnase = c(remove_ctrl1, remove_ctrl2, remove_ctrl3, remove_rnase1, remove_rnase2, remove_rnase3)
rnase_zeros = rnase[-zeros_rnase,]

```



```{r}
#Normalisation
#Control Datensatz
for (i in seq(1, 73, by = 3)) {
  # Iterate through the fractions (each fraction has 3 replicates)
  
  # Compute the sums of every replicate
 sums <- c(sum(ctrl_zeros[, i]), sum(ctrl_zeros[, i + 1]), sum(ctrl_zeros[, i + 2]))
  
  # Compute the mean value of the two closest sums
  diffs <- abs(sums - mean(sums))
  mean_sum <- mean(sums[which.min(diffs)])
  
  # Compute the normalization factors
  norm_factor <- mean_sum / sums
  
  # Multiply the normalization factors with their corresponding replicates
  ctrl_zeros[, i] <- ctrl_zeros[, i] * norm_factor[1]
  ctrl_zeros[, i + 1] <- ctrl_zeros[, i + 1] * norm_factor[2]
  ctrl_zeros[, i + 2] <- ctrl_zeros[, i + 2] * norm_factor[3]
}


#RNAse Datensatz
for (i in seq(1, 73, by = 3)) {
  # Iterate through the fractions (each fraction has 3 replicates)
  
  # Compute the sums of every replicate
 sums <- c(sum(rnase_zeros[, i]), sum(rnase_zeros[, i + 1]), sum(rnase_zeros[, i + 2]))
  
  # Compute the mean value of the two closest sums
  diffs <- abs(sums - mean(sums))
  mean_sum <- mean(sums[which.min(diffs)])
  
  # Compute the normalization factors
  norm_factor <- mean_sum / sums
  
  # Multiply the normalization factors with their corresponding replicates
  rnase_zeros[, i] <- rnase_zeros[, i] * norm_factor[1]
  rnase_zeros[, i + 1] <- rnase_zeros[, i + 1] * norm_factor[2]
  rnase_zeros[, i + 2] <- rnase_zeros[, i + 2] * norm_factor[3]
}
```

```{r}
# Scaling also ein Wertebereich 

ctrl_norm1 = ctrl_zeros[seq(1, ncol(ctrl_zeros), by = 3)]
ctrl_norm2 = ctrl_zeros[seq(2, ncol(ctrl_zeros), by = 3)]
ctrl_norm3 = ctrl_zeros[seq(3, ncol(ctrl_zeros), by = 3)]

rnase_norm1 = rnase_zeros[seq(1, ncol(rnase_zeros), by = 3)]
rnase_norm2 = rnase_zeros[seq(2, ncol(rnase_zeros), by = 3)]
rnase_norm3 = rnase_zeros[seq(3, ncol(rnase_zeros), by = 3)]

#Summer der col / 100 um Quotienten zu erhalten 

#QX = sum(rnase_norm1[1, ])/100
#rnase_norm1[1,1] = rnase_norm1[1,1]/QX

#control
for (i in 1:nrow(ctrl_norm1)) { 
  QX = sum(ctrl_norm1[i, ])/100
  ctrl_norm1[i, ] = ctrl_norm1[i, ]/QX
}

for (i in 1:nrow(ctrl_norm2)) { 
  QX = sum(ctrl_norm2[i, ])/100
  ctrl_norm2[i, ] = ctrl_norm2[i, ]/QX
}

for (i in 1:nrow(ctrl_norm3)) { 
  QX = sum(ctrl_norm3[i, ])/100
  ctrl_norm3[i, ] = ctrl_norm3[i, ]/QX
}

#rnase
for (i in 1:nrow(rnase_norm1)) { 
  QX = sum(rnase_norm1[i, ])/100
  rnase_norm1[i, ] = rnase_norm1[i, ]/QX
}

for (i in 1:nrow(rnase_norm2)) { 
  QX = sum(rnase_norm2[i, ])/100
  rnase_norm2[i, ] = rnase_norm2[i, ]/QX
}

for (i in 1:nrow(rnase_norm3)) { 
  QX = sum(rnase_norm3[i, ])/100
  rnase_norm3[i, ] = rnase_norm3[i, ]/QX
}

```


```{r}
#Smoothing 

```

